# Generated by Django 6.0.6 on 2026-07-04 09:59

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('card_heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('card_text', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('body_text', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('strategy_heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('strategy_desc', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('features', models.JSONField(blank=True, default=list)),
                ('image1', models.CharField(blank=True, max_length=255)),
                ('image2', models.CharField(blank=True, max_length=255)),
                ('image3', models.CharField(blank=True, max_length=255)),
                ('cta_image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ('order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('object_name', models.CharField(help_text="Object key in the media bucket, e.g. 'documents/eng man.pdf'", max_length=255)),
                ('download_file_name', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('answer', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'FAQ item',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FaqSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('subtitle', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('still_have_questions', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('still_have_desc', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('schedule_call', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'FAQ settings',
                'verbose_name_plural': 'FAQ settings',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.SlugField(help_text="Page key, e.g. 'about'", max_length=64, unique=True)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('title', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Page metadata',
                'verbose_name_plural': 'Page metadata',
                'ordering': ('page',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.CharField(help_text='Path or URL to the logo image', max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.PositiveIntegerField(help_text='Number shown with count-up animation')),
                ('unit', models.CharField(blank=True, help_text="e.g. 'mln', 'kW'", max_length=16)),
                ('show_plus', models.BooleanField(default=False)),
                ('icon', models.CharField(choices=[('tshirt', 'T-shirt'), ('briefcase', 'Briefcase'), ('handshake', 'Handshake'), ('bolt', 'Bolt')], max_length=16)),
                ('label', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(max_length=64)),
                ('gender', models.CharField(choices=[('women', 'Women'), ('men', 'Men')], max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('fabric', models.CharField(blank=True, max_length=128)),
                ('composition', models.CharField(blank=True, max_length=128)),
                ('weight', models.CharField(blank=True, max_length=64)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('gender', 'order', 'slug'),
                'constraints': [models.UniqueConstraint(fields=('gender', 'slug'), name='uniq_product_gender_slug')],
            },
        ),
    ]
