# Generated by Django 6.0.6 on 2026-07-04 11:12

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_document_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('subtitle', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('women_label', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('men_label', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Kolleksiyalar',
                'verbose_name_plural': 'Bosh sahifa — Kolleksiyalar',
            },
        ),
        migrations.CreateModel(
            name='HomeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('prefer_talk', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('instant_support', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('call_us', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Kontakt',
                'verbose_name_plural': 'Bosh sahifa — Kontakt',
            },
        ),
        migrations.CreateModel(
            name='HomeCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('cta', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Hamkorlik CTA',
                'verbose_name_plural': 'Bosh sahifa — Hamkorlik CTA',
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('subtitle', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('scroll_label', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Hero',
                'verbose_name_plural': 'Bosh sahifa — Hero',
            },
        ),
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('cta', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Intro',
                'verbose_name_plural': 'Bosh sahifa — Intro',
            },
        ),
        migrations.CreateModel(
            name='HomeWorldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('subtitle', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — Xarita',
                'verbose_name_plural': 'Bosh sahifa — Xarita',
            },
        ),
    ]
