# Generated by Django 6.0.6 on 2026-07-04 11:25

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homecollections_homecontact_homecta_homehero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCtaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('heading', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('description', models.JSONField(blank=True, default=cms.models.empty_localized)),
                ('cta', models.JSONField(blank=True, default=cms.models.empty_localized)),
            ],
            options={
                'verbose_name': 'Bosh sahifa — CTA banner',
                'verbose_name_plural': 'Bosh sahifa — CTA banner',
            },
        ),
    ]
