# Generated by Django 6.0.6 on 2026-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='F.I.O')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('service', models.CharField(blank=True, max_length=160, verbose_name='Xizmat')),
                ('product', models.CharField(blank=True, max_length=160, verbose_name='Mahsulot')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('telegram_status', models.CharField(choices=[('sent', 'Yuborilgan'), ('failed', 'Xato'), ('skipped', "O'tkazib yuborilgan")], default='skipped', max_length=16, verbose_name='Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='Telegram xatosi')),
                ('amocrm_status', models.CharField(choices=[('sent', 'Yuborilgan'), ('failed', 'Xato'), ('skipped', "O'tkazib yuborilgan")], default='skipped', max_length=16, verbose_name='amoCRM')),
                ('amocrm_error', models.TextField(blank=True, verbose_name='amoCRM xatosi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Zayavka',
                'verbose_name_plural': 'Zayavkalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
