# Generated by Django 6.0.6 on 2026-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='Chat ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram sozlamasi',
                'verbose_name_plural': 'Telegram sozlamasi',
            },
        ),
    ]
