# Generated by Django 6.0.6 on 2026-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='about_title',
            field=models.CharField(default='FAYZ-M', max_length=200, verbose_name='Haqida sarlavha'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='app_name',
            field=models.CharField(default='FAYZ-M', max_length=100, verbose_name='Ilova nomi'),
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
